### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Mobilpadde** [kritzware/node-twitchbot#11]
Asking, because I'm getting an error when trying to connect to the chat?

**Comment by kritzware** [comment]
Hi @Mobilpadde! 

I pushed an update recently, so this potentially could have broken something. Everything should work though since the tests pass - maybe you've found a new bug 👍 

- Could you tell me which version you are using? (The number found in your `package.json` file)
- Don't post it here but verify you are using the correct oauth token, which you can find here: [https://twitchapps.com/tmi/](https://twitchapps.com/tmi/)
- Are you getting any visible output? An error message?

Posting a code example of how you are connecting/using the package would be useful as well.

Thanks!

**Comment by Mobilpadde** [comment]
Heya!

Sorry, for not posting more information earlier, but, yea, I was really tired 😁 

Anyhow, I'm using `2.0.2` and getting this error:

```js
{ prefix: 'tmi.twitch.tv',
  server: 'tmi.twitch.tv',
  command: 'err_unknowncommand',
  rawCommand: '421',
  commandType: 'error',
  args: [ 'mobilpadde', 'WHOIS', 'Unknown command' ] }
```

For oauth, I've used this site to generate a token: https://twitchapps.com/tmi/, which, according to their dev-protal, should work?

Sincerely, Mads Cordes

**Comment by kritzware** [comment]
Hello again! 

Apologies for the late reply, I've been travelling all day. I've been able to replicate the issue - I'll push an update later today that should resolve this. 

I'll explain more about it when the patch is pushed 👍

**Comment by Mobilpadde** [comment]
Awesome, sounds great! Can't wait!

**Comment by kritzware** [comment]
I've pushed an update https://github.com/kritzware/node-twitchbot/commit/34efa1afee81bda7e08e121421d0f1b481bd817f which essentially filters out the error `421 WHOIS`. I've encountered the error before and haven't found a good solution yet, perhaps it's an error on the Twitch IRC end? (Hopefully somebody corrects me on this 👍). 

The error doesn't affect the IRC connection however, so you should still be able to connect to a channel. You'll need to update the package as well by doing an `npm install` or `npm install node-twitchbot` - This should push the version to `2.0.3`. The following code snippet below seems to work fine for me 😄 

```javascript
const TwitchBot = require('node-twitchbot')
const Bot = new TwitchBot({
  username: 'botUsername',
  oauth: 'oauth:my-oauth-123-Kappa'
  channel: 'twitch'
})

Bot.connect()
.then(() => {
  console.log('bot connected!')

  Bot.listen((err, chatter) => {
    console.log('['+chatter.channel+'] ' + chatter.user + ': ' + chatter.msg)
  })
  
  Bot.listenFor('Kappa', (err, chatter) => {
    if(!err) {
      Bot.msg('Keepo')
    }
  })
})
```

P.S. If you have any feature ideas/requests please let me know and I'll see what I can do! Pull requests welcome 👍

**Comment by Mobilpadde** [comment]
Awesome, it's working now 😃 Thank you so much!

I haven't tested the 1.* releases, but I really like the feature from the docs about registering multiple commands, seems pretty useful, though, one can live without it 😀 Also, a way to connect to multiple channels would be pretty dang awesome; because, that's really what I need to do.

Otherwise, thanks!

**Comment by kritzware** [comment]
I actually just managed to fix the issue, I'll push another fix shortly. No need for you to update though yet. 

It turns out that Twitch IRC doesn't support IRC `WHO` functionality, but the `node-irc` package used doesn't allow you to stop the `WHO` event emitter. I've forked my own version of `node-irc` which removes the `WHO` calls and use this in `node-twitchbot` now.

I'll be adding the commands functionality from V1 again! 👍 Other things coming soon will probably include more useful functions, such as whispers, timeouts, bans etc.

I'll look into multiple channel connections, but personally I'd recommend creating a new IRC connection for each channel rather than having using one client (the bot) for them all. For now maybe something like the following could help? (Example requires [Bluebird](http://bluebirdjs.com/docs/getting-started.html) for the Promise queue)

<b>EDIT</b>: I tested the code below and it worked fine for me! 👍

```javascript
const TwitchBot = require('node-twitchbot')
const Promise = require('bluebird')

const channels = [
  {
    channel: 'channel1',
    bot: null  
  },
  {
    channel: 'channel2',
    bot: null
  },
  // More channels ...
]

/* Bots join in a queue (works well if you have a lot of channels) */
Promise.resolve(channels).map(channel => {
  channel.bot = new TwitchBot({
    username: 'MrDestructoid',
    oauth: 'oauth:password-kappa-123',
    channel: channel.channel
  })
  channel.bot.connect()
  .then(() => {

    /* Bot methods here */
    channel.bot.listenFor('Kappa', (err, chatter) => {
      if(!err) channel.bot.msg('Keepo')
    })

  })
})
```

**Comment by Mobilpadde** [comment]
Hmm, seems useful, thanks! 👍
